"""added extras to logs_default table

Revision ID: 87d1dd8b4d37
Revises: 6053ab0a97dc
Create Date: 2025-05-06 16:21:07.203684

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87d1dd8b4d37"
down_revision: Union[str, None] = "6053ab0a97dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logs_default", schema=None) as batch_op:
        batch_op.add_column(sa.Column("extras", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logs_default", schema=None) as batch_op:
        batch_op.drop_column("extras")

    # ### end Alembic commands ###
