# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        files: ^(llmstudio/|api/)
        args:
          - "--line-length=99"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(llmstudio/|api/)
        args:
          - "--line-length=99"
          - "--profile=black"
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        files: ^(llmstudio/|api/)
        args:
          - "--max-line-length=99"
