# Step #1: build React frontend
FROM node:16-alpine as build-step
WORKDIR /app/web
COPY ./web/package.json ./
RUN yarn install
COPY ./web ./
RUN yarn build

# Step #2: build Flask API
FROM python:3.9
WORKDIR /app
COPY ./api/requirements.txt ./
RUN pip install -r requirements.txt
COPY --from=build-step /app/web/build ./build
COPY ./api ./api/
ENV FLASK_ENV production

EXPOSE 3001
WORKDIR /app/api
CMD ["gunicorn", "-b", ":3001", "app:app"]