# This Dockerfile builds the React client and Flask API

# Step #1: build React frontend
FROM node:16-alpine as build-step
COPY . . 
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
# COPY package.json ./
RUN yarn install
RUN yarn build

# Step #2: build Flask API
FROM python:3.9
WORKDIR /app
COPY --from=build-step /build ./build
RUN mkdir ./api
COPY ./api ./api/
RUN pip install -r ./api/requirements.txt
ENV FLASK_ENV production

EXPOSE 3001
WORKDIR /app/api
CMD ["gunicorn", "-b", ":3001", "app:app"]