services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: llm-studio-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: llm-studio-client
    ports:
      - "3000:80"
