# Dockerfile for FastAPI backend
FROM python:3.9
WORKDIR /api

# Copying source code
COPY ./api ./

# Installing requirements and dependencies
COPY ./api/requirements.txt ./
COPY ./api/dependencies ./
RUN pip install -r requirements.txt
RUN pip install --no-build-isolation --force-reinstall dependencies/awscli-*-py3-none-any.whl dependencies/boto3-*-py3-none-any.whl dependencies/botocore-*-py3-none-any.whl

EXPOSE 8000

ENV PYTHONPATH=/:$PYTHONPATH
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]